name: Run pytest on push

on:
  push:
    branches:
      - main  # Ejecuta las pruebas cuando se haga push en la rama principal
  pull_request:
    branches:
      - main  # También ejecuta las pruebas en cada pull request

jobs:
  test:
    runs-on: ubuntu-latest  # Ejecutar en un entorno de Ubuntu

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Versión de Python

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Ejecutar pruebas con pytest
      run: pytest
